## numpy tutorial

### import

In [8]:
import numpy as np

### ndarray

In [16]:
price = [180, 215, 210, 210, 188] # python list 
np_price = np.array(price)
print(np_price)
print(type(np_price))

[180 215 210 210 188]
<class 'numpy.ndarray'>


## 4칙연산

In [17]:
# price + 1 # error
price + [1] # append 

[180, 215, 210, 210, 188, 1]

In [18]:
np_price

array([180, 215, 210, 210, 188])

In [19]:
np_price + 9 

array([189, 224, 219, 219, 197])

In [20]:
np_price * 2

array([360, 430, 420, 420, 376])

In [21]:
np_price

array([180, 215, 210, 210, 188])

In [22]:
np_price +[1000]

array([1180, 1215, 1210, 1210, 1188])

In [23]:
np_price > 200 

array([False,  True,  True,  True, False])

## ndarray 간의 연산 

In [24]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [25]:
np_num = np.array([1, 2, 3, 4, 5])
np_num

array([1, 2, 3, 4, 5])

In [26]:
np_price + np_num

array([181, 217, 213, 214, 193])

In [27]:
# np_price + np.array([1, 2]) #error

In [28]:
np_price * np_num

array([180, 430, 630, 840, 940])

In [29]:
np.dot(np_price, np_num)

3020

## filter

In [30]:
np_price

array([180, 215, 210, 210, 188])

In [31]:
high = np_price > 200
high

array([False,  True,  True,  True, False])

In [32]:
np_price[high]

array([215, 210, 210])

In [33]:
np_price[np_price > 200]

array([215, 210, 210])

## filter + count 
200보다 큰 원소는 몇 개? 

In [34]:
np.sum(np_price)

1003

In [35]:
np.mean(np_price)

200.6

In [36]:
np.sum(np_price > 200)

3

In [37]:
len(np_price[np_price > 200])

3

In [38]:
np.mean(np_price > 200)

0.6

In [39]:
len(np_price[np_price > 200]) / len(np_price)

0.6

## True or 1

In [40]:
tf1 = np.array([True, False])
tf1

array([ True, False])

In [41]:
tf1 + 0

array([1, 0])

In [42]:
tf2 = np.array([True, False, 1])
tf2

array([1, 0, 1])

In [43]:
np.array([3, 0, True]) + np.array([2, True, False])

array([5, 1, 1])

## subset, filter

In [44]:
np_price

array([180, 215, 210, 210, 188])

In [45]:
np_price[1]

215

In [46]:
np_price[1:3]

array([215, 210])

In [47]:
np_price[::2]

array([180, 210, 188])

## 2d array

In [48]:
a = [[1,2 ,3],
    [4, 5, 6],
    [7, 8, 9],]
np_a = np.array(a)
np_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np_a[1, 2]

6

In [50]:
np_a[0]

array([1, 2, 3])

In [51]:
np_a[[0, 1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np_a.shape

(3, 3)

## subset, filter

In [53]:
np_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np_a[2,1] #row, col (행,  렬)

8

In [55]:
np_a[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
np_a[:,2:]

array([[3],
       [6],
       [9]])

In [57]:
# np_a[,1] error
np_a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [58]:
np_a[1:,2]

array([6, 9])

In [59]:
np_a[0::2,]

array([[1, 2, 3],
       [7, 8, 9]])

In [60]:
np_a[[0,2],]

array([[1, 2, 3],
       [7, 8, 9]])

## 2d 연산

In [61]:
np_a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [62]:
np_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np_b = np.array([1, 2, 3])
np_b

array([1, 2, 3])

In [64]:
np_a * np_b 

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [65]:
np.matmul(np_a, np_b)

array([14, 32, 50])

## 통계

In [66]:
np_price

array([180, 215, 210, 210, 188])

In [67]:
np.sum(np_price) /len(np_price)

200.6

In [68]:
np.mean(np_price)

200.6

In [69]:
np.std(np_price)

13.908270920570969

In [70]:
np_weight = np.array([100, 120, 80, 150, 90])

In [71]:
np.corrcoef(np_weight, np_price)

array([[1.        , 0.40325126],
       [0.40325126, 1.        ]])

## None type

In [72]:
a = None 

In [73]:
type(a)

NoneType

In [74]:
a + 3

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [75]:
a = np.NaN

In [76]:
a

nan

In [77]:
a + 3

nan

In [78]:
a = np.array([1, 2, 3, 4, np.NaN])
a

array([ 1.,  2.,  3.,  4., nan])

In [79]:
np.sum(a)

nan

In [80]:
aaa = np.array([1, 2, 3])
np.hstack((aaa, np.array([4, 5])))

array([1, 2, 3, 4, 5])

In [83]:
aaaa = np.array([1, 1, 1,1, np.nan, 3, 2, np.nan])
aaaa = aaaa[~np.isnan(aaaa)]
aaaa

array([1., 1., 1., 1., 3., 2.])

In [84]:
np.nansum(aaaa)

9.0